# Simplified node table structure for testing parser
data: &can-info
  can-info:
    verifyOnRead: true
    verifyOnWrite: true
services:
  aws-near: &aws-near
    type: aws-near
    service-properties:
      serviceType: aws
      accessMode: near-line
      region: us-west-2
  aws-std: &aws-std
    type: aws-std
    service-properties:
      serviceType: aws
      accessMode: on-line
      storageClass: Standard
      region: us-west-2
  minio: &minio
    type: minio
    service-properties:
      serviceType: minio
      endPoint: "{!ENV: minio_endpoint}"
      accessKey: "{!SSM: minio-accessKey}"
      secretKey: "{!SSM: minio-secretKey}"
environments:
  production:
    nodes:
      - &naws
        # AWS Standard
        identifier: 100
        <<: *aws-std
        bucket: aws-prod
        <<: *can-info
      - &nglacier
        # AWS Glacier
        identifier: 200
        <<: *aws-near
        bucket: glacier-prod
        <<: *can-info
      - &nminio
        # Minio
        identifier: 300
        <<: *minio
        bucket: minio-prod
        <<: *can-info
  stage:
    nodes:
      - <<: *naws
        bucket: aws-stg
      - <<: *nglacier
        bucket: glacier-stg
      - <<: *nminio
        bucket: glacier-stg
